apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: synapse-db
  namespace: knarr
spec:
  parameters:
    storageSize: 2Gi
    version: "15"
    replicas: 1
    databaseName: synapse
  compositionSelector:
    matchLabels:
      provider: percona
      service: postgresql
